spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: create
  datasource:
    username: mysql
    password: mysql
    url: jdbc:mysql://localhost:3310/task_management_system_db
#    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      schema: task_management_system_schema
      connection-ini-sql: task_management_system_schema
