spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: create
  datasource:
    username: mysql
    password: mysql
    url: jdbc:mysql://localhost:3310/task_management_system_db
    hikari:
      schema: task_management_system_schema
      connection-ini-sql: task_management_system_schema


app:
  jwt:
    secret: taskManagementSystemSecretKey
    tokenExpiration: 3m
    refreshTokenExpiration: 30m

logging:
  level:
    root: info