services:

  mysql:
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=task_management_system_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql